# Generated by Django 5.0.6 on 2024-06-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='strip_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
